/**
 * Custom Style Dictionary Formats
 * React Native Paper 테마 호환 TypeScript 생성
 */

module.exports = {
  'typescript/react-native-theme': function({ dictionary, options }) {
    return `/**
 * Auto-generated by Style Dictionary
 * DO NOT EDIT MANUALLY
 */

import { MD3LightTheme } from 'react-native-paper';
import type { MD3Theme } from 'react-native-paper';

export const customColors = {
${dictionary.allTokens
  .filter(token => token.path[0] === 'color')
  .map(token => `  ${token.name}: '${token.value}',`)
  .join('\n')}
} as const;

export const customTypography = {
${dictionary.allTokens
  .filter(token => token.path[0] === 'typography')
  .map(token => {
    // fontSize, fontWeight, lineHeight 는 숫자로, fontFamily는 문자열로
    const isNumeric = token.path[1] === 'fontSize' || token.path[1] === 'fontWeight' || token.path[1] === 'lineHeight';
    const value = isNumeric ? parseFloat(token.value) : `'${token.value}'`;
    return `  ${token.name}: ${value},`;
  })
  .join('\n')}
} as const;

export const customSpacing = {
${dictionary.allTokens
  .filter(token => token.path[0] === 'spacing')
  .map(token => `  ${token.name}: ${token.value},`)
  .join('\n')}
} as const;

export const theme: MD3Theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: customColors.colorPrimaryDefault,
    secondary: customColors.colorSecondaryDefault,
    error: customColors.colorError,
    background: customColors.colorBackground,
    surface: customColors.colorSurface,
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onError: '#FFFFFF',
    onBackground: customColors.colorNeutralDark,
    onSurface: customColors.colorNeutralDark,
  },
  fonts: {
    ...MD3LightTheme.fonts,
    // Noto Sans KR 설정은 별도 fontConfig로 처리
  }
};

export default theme;
`;
  }
};
